#!/bin/csh

cd ~/Project_Twilight/src
make wipe
cd ~/Project_Twilight/area
rm core
cd ~

    set index = 1000
    while ( 1 )
	set logfile = $index
	if ( ! -e $logfile.tgz ) break
	@ index++
    end

tar -cvf player-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/player/
gzip player-`date "+%d_%b_%Y_%H_%M"`.tar
mv player-`date "+%d_%b_%Y_%H_%M"`.tar.gz player-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx player-`date "+%d_%b_%Y_%H_%M"`.tgz

tar -cvf area-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/area/
gzip area-`date "+%d_%b_%Y_%H_%M"`.tar
mv area-`date "+%d_%b_%Y_%H_%M"`.tar.gz area-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx area-`date "+%d_%b_%Y_%H_%M"`.tgz

tar -cvf src-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/src/
gzip src-`date "+%d_%b_%Y_%H_%M"`.tar
mv src-`date "+%d_%b_%Y_%H_%M"`.tar.gz SRC-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx SRC-`date "+%d_%b_%Y_%H_%M"`.tgz

ls mud/log/ >> log

tar -cvf mud-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/ --exclude-from ~/log
gzip mud-`date "+%d_%b_%Y_%H_%M"`.tar
mv mud-`date "+%d_%b_%Y_%H_%M"`.tar.gz MUD-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx MUD-`date "+%d_%b_%Y_%H_%M"`.tgz

rm log

#tar -cvf web.tar public_html/projecttwilight/
#gzip web.tar
#mv web.tar.gz WEB.tgz
#chmod og-rwx WEB.tgz

cd ~/Project_Twilight/src/
make

cd ~
mv *.tgz ./backup

rm ~/Project_Twilight/src/completedbackup
