#!/bin/csh

cd ~/Project_Twilight/src
make wipe
cd ~/Project_Twilight/area
rm core
cd ~

    set index = 1000
    while ( 1 )
	set logfile = $index
	if ( ! -e $logfile.tgz ) break
	@ index++
    end

tar -cvf Project_Twilight-player-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/player/
gzip Project_Twilight-player-`date "+%d_%b_%Y_%H_%M"`.tar
mv Project_Twilight-player-`date "+%d_%b_%Y_%H_%M"`.tar.gz Project_Twilight-player-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx Project_Twilight-player-`date "+%d_%b_%Y_%H_%M"`.tgz

tar -cvf Project_Twilight-area-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/area/
gzip Project_Twilight-area-`date "+%d_%b_%Y_%H_%M"`.tar
mv Project_Twilight-area-`date "+%d_%b_%Y_%H_%M"`.tar.gz Project_Twilight-area-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx Project_Twilight-area-`date "+%d_%b_%Y_%H_%M"`.tgz

tar -cvf Project_Twilight-src-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/src/
gzip Project_Twilight-src-`date "+%d_%b_%Y_%H_%M"`.tar
mv Project_Twilight-src-`date "+%d_%b_%Y_%H_%M"`.tar.gz Project_Twilight-SRC-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx Project_Twilight-SRC-`date "+%d_%b_%Y_%H_%M"`.tgz

ls mud/log/ >> log

tar -cvf Project_Twilight-mud-`date "+%d_%b_%Y_%H_%M"`.tar Project_Twilight/ --exclude-from ~/log
gzip Project_Twilight-mud-`date "+%d_%b_%Y_%H_%M"`.tar
mv Project_Twilight-mud-`date "+%d_%b_%Y_%H_%M"`.tar.gz Project_Twilight-MUD-`date "+%d_%b_%Y_%H_%M"`.tgz
chmod og-rwx Project_Twilight-MUD-`date "+%d_%b_%Y_%H_%M"`.tgz

rm log

#tar -cvf web.tar public_html/projecttwilight/
#gzip web.tar
#mv web.tar.gz WEB.tgz
#chmod og-rwx WEB.tgz

cd ~/Project_Twilight/src/
make

cd ~
mv *.tgz ./backup

rm ~/Project_Twilight/src/completedbackup
